#:schema node_modules/wrangler/config-schema.json
name = "marketing-cdn"
main = "src/index.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

# Custom domain configuration
#routes = [
#    { pattern = "cdn.designxdevelop.com", custom_domain = true }
#]

# Bind an R2 Bucket for CDN storage
[[r2_buckets]]
binding = "CDN_BUCKET"
bucket_name = "marketing-cdn"
